#### Hugo variables
baseURL = "/"

# comment if you want to disable multilingual support.
# DefaultContentLanguage = "en"

# If you want all of the languages to be put below their respective language code,
# enable DefaultContentLanguageInSubdir = true. Without enabling it english content
# will be in the root and other languages in their respective subfolder such as /sv/.
# See [Languages] settings at the end of this file.

# Use this languageCode if it's not a multilingual site and also remove all language blocks and menus in the language sections to disable multilingual support.
# language blocks.
# Language
languageCode = "en-us"
title = " "
features = ["studio60", "one page", "responsive"]
min_version = "0.0.dev"
canonifyurls = true
#### Pagination
paginate = 3

#paginatePath = "pagination"


#### Enable Disqus integration
#disqusShortname = "shortname"

[permalinks]
post = "/:year/:month/:day/:filename/"
code = "/:filename/"
page = "/:slug/"

[taxonomies]
tag = "tags"
topic = "topics"

[params]
  Author = "STUDIO60"
  DateForm = "Mon, Jan 2, 2006"
  Designer = "Studio60"
  DesignerSignature="Designed by Studio60"
  Description = " "
  email = " mailme@mail.com " #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 6 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = false #set to false to exclude read time from header of post
  theme = " "


[author]
name = "yourname"
email = "yourname@example.com"

[menu]
#[[menu.main]]
#  name = "Home"
#  url = "#one"
#  weight = -300
[[menu.main]]
  name = "About"
  url = "#two"
  weight = -280
[[menu.main]]
  name = "Blog"
  url = "#three"
  weight = -260
[[menu.main]]
  name = "Portfolio"
  url = "#four"
  weight = -240
[[menu.main]]
  name = "Contact"
  url = "#five"
  weight = -220

[[menu.sidebar]]
  name = "Blog page"
  url = "https://example.com"
[[menu.sidebar]]
  name = "Other page"
  url = "https://example.com"
[[menu.sidebar]]
  name = "contact form"
  url = "https://example.com"
[[menu.sidebar]]
  name = "Designer Page"
  url = "https://example.com"
[[menu.sidebar]]
  name = "Link 2"
  url = "https://example.org"
